### ISSUE TITLE
Please publish to npm

### ISSUE THREAD

**Issue by ericelliott** [mozilla/web-components#6]
I'd love to build on this in an npm package. Will you please publish it to npm, so I don't have to use the hacky github-style include?

**Comment by pennyfx** [comment]
We don't have plans to publish to NPM, but you can use Bower instead.

http://twitter.github.com/bower/

You'll need to add a component.json file to your project.  

Here's an example.   https://github.com/x-tag/x-tags-org/blob/master/component.json

Then run
$ bower install

This will download the components to ./component/. 

We use grunt tasks to build and minify our client side scripts to be used in our application.

https://github.com/x-tag/x-tags-org/blob/master/Gruntfile.js

**Comment by ericelliott** [comment]
What does Bower give you that npm doesn't? Seems to me, it just cuts off access to lots of great packages that already exist on npm (including lots of browser-side packages).

**Comment by mattdesl** [comment]
:+1:
