### ISSUE TITLE
insertedCallback is not called when the element is being upgraded

### ISSUE THREAD

**Issue by mnieper** [mozilla/web-components#8]
When a custom element, e.g. <div is="x-foo"></div> is part of the HTML and is being upgraded by document.register.js (loaded in the head of the page), the insertedCallback does not seem to be called.

This seems to be against the current version of the spec: https://dvcs.w3.org/hg/webcomponents/raw-file/tip/spec/custom/index.html#registering-custom-elements.

In fact, the behaviour of the polyfill makes it hard, for example, to register event handlers whenever the element is inserted (or already inside) the document and to deregister them when the element is taken out.

Google's Polymer/Toolkitchen polyfill does not show this behaviour.

**Comment by mnieper** [comment]
Great! I see that you have added the relevant code. Now it works for me.

**Comment by csuwildcat** [comment]
Yep, should be 100% up to date now ;)
