### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by umaar** [mozilla/web-components#9]
Could we get more insight into what this project aims to solve, what it can be used for and future plans?

It could also be worth comparing this project with similar ones such as [Polymer](https://github.com/Polymer/polymer).

**Comment by fwenzel** [comment]
I think this repository is outdated.

The web components library is x-tag at github.com/x-tag and x-tags.org, and the UI library built with web components is Brick http://mozilla.github.io/brick .

**Comment by umaar** [comment]
Got it, thanks!
